name: Run Vitest on push to main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test: #Actual job name
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Setup Node 22"
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: "Clean install packages"
        run: npm ci
      - name: "Run tests"
        run: npx vitest run
      # There can be a next step to make a test report as an articaft
      # IF something fails you can check the reports in github's artifact repos
